const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#A855F7',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#0F0F0F',
    cardForeground: '#FFFFFF',
    primary: '#A855F7',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A1A',
    secondaryForeground: '#FFFFFF',
    muted: '#1A1A1A',
    mutedForeground: '#666666',
    accent: '#A855F7',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#222222',
    input: '#1A1A1A',
    // Antigravity-specific
    neonPurple: '#A855F7',
    neonPurpleDim: '#7C3AED',
    surface: '#111111',
    surfaceElevated: '#1C1C1E',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#A855F7',
    background: '#000000',
    foreground: '#FFFFFF',
    card: '#0F0F0F',
    cardForeground: '#FFFFFF',
    primary: '#A855F7',
    primaryForeground: '#FFFFFF',
    secondary: '#1A1A1A',
    secondaryForeground: '#FFFFFF',
    muted: '#1A1A1A',
    mutedForeground: '#666666',
    accent: '#A855F7',
    accentForeground: '#FFFFFF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    border: '#222222',
    input: '#1A1A1A',
    neonPurple: '#A855F7',
    neonPurpleDim: '#7C3AED',
    surface: '#111111',
    surfaceElevated: '#1C1C1E',
  },
  radius: 12,
};

export default colors;
